words=[
   "Abaft",
   "Abeam",
   "Amidships",
   "Athwartships",
   "Backstay",
   "Baggywrinkle",
   "Batten",
   "Beam",
   "Beat",
   "Bilge",
   "Broach",
   "Broadreach",
   "Bulkhead",
   "Cleat",
   "Closehauled",
   "Course",
   "Downhaul",
   "Draft",
   "Fairlead",
   "Forestay",
   "Freeboard",
   "Genoa",
   "Gooseneck",
   "Goosewing",
   "Gybe",
   "Halyard",
   "Headway",
   "Jackstay",
   "Kedge",
   "Keel",
   "Ketch",
   "Leech",
   "Leeward",
   "Leeway",
   "Mizzen",
   "Outhaul",
   "Port",
   "Pulpit",
   "Quarter",
   "Reach",
   "Reef",
   "Roach",
   "Schooner",
   "Shackle",
   "Sloop",
   "Spinnaker",
   "Starboard",
   "Spreaders",
   "Tacking",
   "Windward",
   "Yawl",
]
 
definition = [
   "towards the boats stern",
   "at right angles to the centre-line of the boat",
   "the centre of the boat, athwartships and fore-and-aft",
   "at right angles to the fore-and-aft line of the boat",
   "a stay that supports the mast from aft and prevents its forward movement",
   "rope, teased out, plaited together and wound around stays, shrouds etc. to prevent chaffing",
   "a light, flexible strip, fed into a batten pocket at the leech of the sail to support the roach.",
   "the maximum breadth of the boat",
   "to sail a zigzag course towards the wind, close-hauled on alternate tacks",
   "the lower, round part inside the hull where water collects",
   "when a boat running downwind slews broadside to the wind and heels dangerously. It is caused by heavy following seas or helmsman' error.",
   "the point of sailing between a beam reach and a run when the wind blows over the quarter",
   "structural partition wall in a boat normally fitted athwartships",
   "a wooden, metal or plastic fitting around which a rope is secured",
   "the point of sailing closest to the wind; see also beat.",
   "the direction in which a vessel is steered, usually given in degrees, true, magnetic or compass.",
   "a rope fitted to pull down a sail or spar",
   "the vertical distance from the waterline to the lowest point of the keel",
   "a fitting through which a line is run to alter the direction of the lead of the line",
   "the foremost stay running from the masthead to the stemhead, to which the foresail is hanked.",
   "vertical distance between the waterline and the top of the deck.",
   "a large headsail in various sizes, which overlaps the mainsail and is hoisted in light to fresh winds on all points of sailing.",
   "the fitting attaching the boom to the mast, allowing it to move in all directions",
   "to boom out the headsail to windward on a run by using a whisker pole to hold the sail on the opposite side to the mainsail.",
   "to change from one tack to another by turning the stern through the wind.",
   "rope used to hoist and lower sails.",
   "the forward movement of a boat through the water",
   "a line running fore-and-aft on both sides of the boat to which safety harnesses are clipped.",
   "a small, light second anchor",
   "the main backbone of the boat to which a ballast keel is bolted or through which the centre-board passes.",
   "a two-masted sailing vessel with a mizzen mast slightly smaller than the main and stepped forward of the rudder stock/post",
   "the after edge of a triangular sail",
   "away from the wind, the direction to which the wind blows",
   "the sideways movement off its course as a result of the wind blowing on one side of the sails and hull.",
   "the shorter after-mast on a ketch or yawl.",
   "a rope used to pull out the foot of a sail.",
   "the left hand side of the boat looking forward.",
   "a metal guard rail fitted at the bows of a boat to provide safety for the crew.",
   "the portion of the boat midway between the stern and the beam",
   "to sail with the wind approximately on the beam , all sailing points between running and close hauled.",
   "to reduce the sail area by folding or rolling surplus material on the boom or forestay.",
   "the curved part of the leech of a sail which extends beyond the direct line from head to clew",
   "a boat with two or more masts with the mainmast aftermost",
   "a metal link with a removable bolt across the open end, of various shapes",
   "a single-masted sailing boat with one mainsail and one headsail",
   "a large, light balloon shaped sail used when reaching or running.",
   "right-hand side of the boat looking forward",
   "horizontal struts attached to the mast which extend to the shrouds and help support the mast",
   "working to windward by sailing close-hauled on alternate courses so that the wind is first and one side then on the other",
   "the direction from which the wind blows toward the wind (opposite to leeward)",
   "a two-masted boat with the mizzen stepped aft of the rudder stock / post"
]